# Jekyll configuration for Hydejack theme
# Documentation: https://hydejack.com/docs/

# Theme
theme: jekyll-theme-hydejack

# Site settings
title: Portfolio
tagline: Health Tech & Streaming Solutions
description: Innovative solutions in healthcare technology and streaming platforms
url: https://open-access-policies.github.io
baseurl: ""

# Author information
author:
  name: Your Name
  email: your.email@example.com
  picture: /assets/img/logo.png

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  math_engine_opts: {}
  footnote_backlink: '&#x21a9;&#xfe0e;'

# Hydejack settings
hydejack:
  version: 9.2.1
  copyright: © 2025. CC-BY-SA-4.0 Licensed

# Plugins
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache

# Optional plugins
optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
  with_frontmatter: true

relative_links:
  collections: true

titles_from_headings:
  strip_title: true
  collections: true



# 3rd Party Integrations
google_analytics: # Your Google Analytics tracking ID
google_fonts: false # Disable Google Fonts to use local Latin Modern Roman
font_heading: "'LatinModernRoman', 'Latin Modern Roman', serif"
font: "'LatinModernRoman', 'Latin Modern Roman', serif"

# Social media and contact links
social:
  name: Your Name
  links:
    - https://twitter.com/username
    - https://github.com/open-access-policies

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.sh"
  - README.md

# Include
include:
  - .well-known
