# Jekyll configuration for Hydejack theme
# Documentation: https://hydejack.com/docs/
# --- Site Settings ---
title: "Open Access Policies"
description: "Open source policies for any company."
# url: "https://open-access-policies.github.io"
baseurl: "/health-tech"

# --- Hydejack Specific Settings ---
hydejack:
  theme: theme-base-08
  sticky_sidebar: true 
  accent_color: "#bababa" # Solid gray color for sidebar
  invert_sidebar: false # Changed to false since we're using a light color
  theme_color: "#bababa"

# Theme
remote_theme: "hydecorp/hydejack@v9.2.1"

# Site settings
title: Open Access Policies
tagline: Open source policies for any company.
description: Comprehensive policies for organizations to adapt and implement.
url: https://open-access-policies.github.io
baseurl: ""

# Author information
author:
  name   : "Sean Todd"
  avatar : "/assets/images/headshot.jpg"
  bio    : "A helpful CISO looking for his next challenge."
  links  :
    - label: "GitHub"
      url: "https://github.com/descentintomael"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/seanmtodd/"
  # --- Author Social Links ---
  social:
    github: open-access-policies
    email: sean@openaccesspolicies.org
    linkedin: seanmtodd

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  math_engine_opts: {}
  footnote_backlink: '&#x21a9;&#xfe0e;'

# Hydejack settings
hydejack:
  version: 9.2.1
  copyright: © 2025. CC-BY-SA-4.0 Licensed

# Plugins
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache

# Optional plugins
optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
  with_frontmatter: true

relative_links:
  collections: true

titles_from_headings:
  strip_title: true
  collections: true



# 3rd Party Integrations
google_analytics: # Your Google Analytics tracking ID
google_fonts: false # Disable Google Fonts to use local Latin Modern Roman
font_heading: "'LatinModernRoman', 'Latin Modern Roman', serif"
font: "'LatinModernRoman', 'Latin Modern Roman', serif"

# Social media and contact links
social:
  name: Your Name
  links:
    - https://twitter.com/username
    - https://github.com/open-access-policies

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.sh"
  - README.md

# Include
include:
  - .well-known
