# --- Site Settings ---
title: "Open Access Policies"
description: "Free to use policies for your organization."
url: "https://open-access-policies.github.io"
baseurl: "/"

# --- Hydejack Specific Settings ---
hydejack:
  theme: theme-base-08
  sticky_sidebar: true 
  accent_color: "#bababa" # Solid gray color for sidebar
  invert_sidebar: false # Changed to false since we're using a light color
  theme_color: "#bababa"
  
# Additional CSS files
additional_css:
  - /assets/css/main.css
  - /assets/css/latin-modern-fonts.css

# --- Favicon Settings ---
favicon: /assets/images/logo.png


# --- Defaults ---
# This is the critical fix. We are telling Jekyll to use the 'page'
# layout for every document inside every one of your collections.
# This will override any incorrect 'layout' settings in the individual files.
defaults:
  # Add this global default for all pages
  - scope:
      path: "" # This means all files
    values:
      hide_title: true # Add this line to hide page titles
      no_page_title: true # This removes the page title from the top of each page.
      accent_color: "#bababa" # Solid gray color

# --- Build settings ---
remote_theme: "hydecorp/hydejack@v9.2.1"
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# --- Sass configuration ---
sass:
  sass_dir: _sass
  style: expanded

author:
  name   : "Sean Todd"
  avatar : "/assets/images/headshot.jpg"
  bio    : "A helpful CISO looking for his next challenge."
  links  :
    - label: "GitHub"
      url: "https://github.com/descentintomael"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/seanmtodd/"
  # --- Author Social Links ---
  social:
    github: open-access-policies
    email: sean@openaccesspolicies.org
    linkedin: seanmtodd
  #   rss: true # To enable the RSS feed icon